### ISSUE TITLE
What's new section

### ISSUE THREAD

**Issue by JonnyGadd** [I-A-C/ExodusReduxRepo#17]
Hi apologies this is not an issue but can't add it in a request section, would it be possible to add a what's new section in the addon so we can see latest updates etc? Numbers placenta etc have them I think numbers is called numbers news or something :) thanks for the hard work!

**Comment by turtlestv** [comment]
Look at commits or comments there are short information

**Comment by JonnyGadd** [comment]
Inside the addon?

**Comment by turtlestv** [comment]
I read that wrong. Yes it can be addded.

**Comment by JonnyGadd** [comment]
Awesome thankyou really appreciate it!

**Comment by JonnyGadd** [comment]
I can't find the commits section on here, where can i see the update changes?

**Comment by SerpentDrago** [comment]
https://github.com/I-A-C/ExodusReduxRepo/commits/master

**Comment by SerpentDrago** [comment]
I-A-C  , Please close down this and other comments / issues that are solved or done  ! ?
