### ISSUE TITLE
Scraping minor error

### ISSUE THREAD

**Issue by JonnyGadd** [I-A-C/ExodusReduxRepo#19]
Hi sometimes when clicking on a tv show or film it will only pull very few 1080 links using RD, if I do the scrape again for the same show it will then scrape a lot more, for example I just searched The Purge Episode 7, the first time it gave me 7 1080p, the second time round it scrapped 33, this is not an issue as it's only matter of letting it do the scrape again but what would be causing it to happen? This is using Redux on my Nvidia shield, numbers also does this if it's any help. Thanks!

**Comment by host505** [comment]
It's always been like that, reason is cache. Scraping results get cached (I think for an hour), so on the second search they get fetched from the cache, way faster, leaving time for more providers to bring results, that may timed-out on the first attempt.

**Comment by SerpentDrago** [comment]
So , Whats happening is its timing out the first time , displaying the results . then the 2nd time it shows already cached results from first search and is able to get to a few more providers before results . 

You can try increasing the timeout in settings . and disabling Pre Termination  (if that exists , i can't remember )  

but it also could be kodi internal timeout . try the above  . Good luck !


You can also try disabling providers you know you dont' like or never return results . less providers / scrapers . more time it has with existing ones

**Comment by SerpentDrago** [comment]
Its cause some scrapers are "hanging up " if we could figure out which ones are hanging up for you , you could remove them and it would be better .
