### ISSUE TITLE
Only Scrape RD

### ISSUE THREAD

**Issue by JonnyGadd** [I-A-C/ExodusReduxRepo#23]
Hi guys, I never use non RD links, is there a setting you could add to the addon so that Redux will only scrape RD sources and not free ones?

**Comment by SerpentDrago** [comment]
Please post in the correct github 

plugin.video.exodusredux  or / script.module.lambdascrapers

I know its confusing but this is the old Repo . it only exists for legacy reasons

**Comment by drinfernoo** [comment]
@JonnyGadd Isn't there already a "Debrid Sources Only" option in Exodus Redux? Is that not functioning together with LambdaScrapers?
