### ISSUE TITLE
fix trakt auth in add-on settings

### ISSUE THREAD

**Issue by iCanuck** [I-A-C/ExodusReduxRepo#8]
Trakt Authorization action in settings is broken... in Leia you can't have two of the same setting id with two different setting types. Easy fix, change line#74

from

`<setting id="trakt.user" type="action" label="32306" option="close" action="RunPlugin(plugin://plugin.video.exodusredux/?action=authTrakt)" />`

to

`<setting id="trakt.auth" type="action" label="32306" option="close" action="RunPlugin(plugin://plugin.video.exodusredux/?action=authTrakt)" />`

**Comment by host505** [comment]
That's useful info, thanks!
However, if I'm not mistaken, doing what you suggest affects the "[other](https://github.com/I-A-C/ExodusReduxRepo/blob/master/plugin.video.exodusredux/resources/settings.xml#L7)" setting with the same id too, and that one is used on many functions within the add-on, trakt auth included.
What worked for me is, along with your suggested change, to modify the aforementioned line from:
`<setting id="trakt.user" type="text" default="" visible="false" />`
to:
`<setting id="trakt.user" type="text" value="trakt.auth" default="" visible="true" />`

**Comment by iCanuck** [comment]
> 
> 
> That's useful info, thanks!
> However, if I'm not mistaken, doing what you suggest affects the "[other](https://github.com/I-A-C/ExodusReduxRepo/blob/master/plugin.video.exodusredux/resources/settings.xml#L7)" setting with the same id too, and that one is used on many functions within the add-on, trakt auth included, which they break.
> What worked for me is, along with your suggested change, to modify the aforementioned line from:
> `<setting id="trakt.user" type="text" default="" visible="false" />`
> to:
> `<setting id="trakt.user" type="text" value="trakt.auth" default="" visible="false" />`
> 
> edit: I have to say that this hasn't be tested with ExodusRedux, but another incursion-based fork.
